// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"

void Start_Animation( lv_obj_t *TargetObject, int delay);
// SCREEN: ui_Main
void ui_Main_screen_init(void);
extern lv_obj_t *ui_Main;
extern lv_obj_t *ui_PanelInit;
extern lv_obj_t *ui_WiFiIsConnect;
extern lv_obj_t *ui_WiFiNoConnect;
extern lv_obj_t *ui_WelcomeLab;
extern lv_obj_t *ui_Electricity;
extern lv_obj_t *ui_PanelTime;
extern lv_obj_t *ui_LabelTime1;
extern lv_obj_t *ui_LabelTime2;
extern lv_obj_t *ui_TabViewApp;
extern lv_obj_t *ui_TabPageApp;
extern lv_obj_t *ui_PanelSet;
void ui_event_ToSet( lv_event_t * e);
extern lv_obj_t *ui_ToSet;
extern lv_obj_t *ui_LabelSet;
extern lv_obj_t *ui_PanelSerial;
void ui_event_ToSerial( lv_event_t * e);
extern lv_obj_t *ui_ToSerial;
extern lv_obj_t *ui_LabelSerial;
extern lv_obj_t *ui_PanelWeather;
void ui_event_ToWeather( lv_event_t * e);
extern lv_obj_t *ui_ToWeather;
extern lv_obj_t *ui_LabelWeather;
extern lv_obj_t *ui_PanelMusic;
void ui_event_ToMusic( lv_event_t * e);
extern lv_obj_t *ui_ToMusic;
extern lv_obj_t *ui_LabelMusic;
extern lv_obj_t *ui_PanelGPT;
void ui_event_ToGPT( lv_event_t * e);
extern lv_obj_t *ui_ToGPT;
extern lv_obj_t *ui_LabelGPT;
extern lv_obj_t *ui_PanelGame;
void ui_event_ToGame( lv_event_t * e);
extern lv_obj_t *ui_ToGame;
extern lv_obj_t *ui_LabelGame;
extern lv_obj_t *ui_PanelCal;
void ui_event_ToCal( lv_event_t * e);
extern lv_obj_t *ui_ToCal;
extern lv_obj_t *ui_LabelCal;
extern lv_obj_t *ui_PanelAbout;
void ui_event_ToAbout( lv_event_t * e);
extern lv_obj_t *ui_ToAbout;
extern lv_obj_t *ui_LabelAbout;
// SCREEN: ui_Serial
void ui_Serial_screen_init(void);
extern lv_obj_t *ui_Serial;
void ui_event_SerialBackToMain( lv_event_t * e);
extern lv_obj_t *ui_SerialBackToMain;
void ui_event_TextSerial( lv_event_t * e);
extern lv_obj_t *ui_TextSerial;
void ui_event_SerialSend( lv_event_t * e);
extern lv_obj_t *ui_SerialSend;
extern lv_obj_t *ui_TextSerialRx;
void ui_event_SerialDelete( lv_event_t * e);
extern lv_obj_t *ui_SerialDelete;
void ui_event_RateSelect( lv_event_t * e);
extern lv_obj_t *ui_RateSelect;
void ui_event_KeyboardSerial( lv_event_t * e);
extern lv_obj_t *ui_KeyboardSerial;
// SCREEN: ui_Set
void ui_Set_screen_init(void);
extern lv_obj_t *ui_Set;
void ui_event_SetBackToMain( lv_event_t * e);
extern lv_obj_t *ui_SetBackToMain;
extern lv_obj_t *ui_PanelSetLight;
void ui_event_SetLight( lv_event_t * e);
extern lv_obj_t *ui_SetLight;
extern lv_obj_t *ui_LabelLightValue;
extern lv_obj_t *ui_LabelLight;
extern lv_obj_t *ui_PanelWiFi;
extern lv_obj_t *ui_PanelScanWiFi;
void ui_event_EnterPassword( lv_event_t * e);
extern lv_obj_t *ui_EnterPassword;
extern lv_obj_t *ui_RollerWiFi;
void ui_event_RollerGetWiFi(lv_event_t * e);
extern lv_obj_t *ui_ConnectStatus;
extern lv_obj_t *ui_LabelWiFi;
void ui_event_OnOffWiFi( lv_event_t * e);
extern lv_obj_t *ui_OnOffWiFi;
extern lv_obj_t *ui_SpinnerWaitWiFi;
extern lv_obj_t *ui_PanelConnect;
void ui_event_KeyboardWiFi( lv_event_t * e);
extern lv_obj_t *ui_KeyboardWiFi;
extern lv_obj_t *ui_PanelPassword;
extern lv_obj_t *ui_TextWiFiPassword;
extern lv_obj_t *ui_LabelWiFiName;
void ui_event_CancelEnter( lv_event_t * e);
extern lv_obj_t *ui_CancelEnter;
// SCREEN: ui_Weather
void ui_Weather_screen_init(void);
extern lv_obj_t *ui_Weather;
extern lv_obj_t *ui_TabWeather;
extern lv_obj_t *ui_TabToday;
extern lv_obj_t *ui_Location;
extern lv_obj_t *ui_Code;
extern lv_obj_t *ui_Temp;
extern lv_obj_t *ui_LabelLocation;
extern lv_obj_t *ui_LabelCode;
extern lv_obj_t *ui_LabelTemp;
extern lv_obj_t *ui_LabelUpdateTime;
extern lv_obj_t *ui_TabFuture;
extern lv_obj_t *ui_LabelAllWeather;
extern lv_obj_t *ui_RollerWeather;
void ui_event_UpdateWeather( lv_event_t * e);
extern lv_obj_t *ui_UpdateWeather;
void ui_event_WeatherBackToMain( lv_event_t * e);
extern lv_obj_t *ui_WeatherBackToMain;
extern lv_obj_t *ui_LabelNoWiFI;
extern lv_obj_t *ui____initial_actions0;
// SCREEN: ui_Music
void ui_Music_screen_init(void);
extern lv_obj_t *ui_Music;
void ui_event_MusicBackToMain( lv_event_t * e);
extern lv_obj_t *ui_MusicBackToMain;
void ui_event_RollerMusic( lv_event_t * e);
extern lv_obj_t *ui_RollerMusic;
void ui_event_SliderVoice( lv_event_t * e);
extern lv_obj_t *ui_SliderVoice;
extern lv_obj_t *ui_PanelMusicSet;
void ui_event_StartMusic( lv_event_t * e);
extern lv_obj_t *ui_StartMusic;
void ui_event_ChangeMusic( lv_event_t * e);
extern lv_obj_t *ui_ChangeMusic;
extern lv_obj_t *ui_Label1;
// SCREEN: ui_GPT
void ui_GPT_screen_init(void);
extern lv_obj_t *ui_GPT;
void ui_event_GPTBackToMain( lv_event_t * e);
extern lv_obj_t *ui_GPTBackToMain;
extern lv_obj_t *ui_GPTQuestion;
extern lv_obj_t *ui_LabelGPTQFace;
extern lv_obj_t *ui_TextAreaQuestion;
extern lv_obj_t *ui_GPTAnswer;
extern lv_obj_t *ui_LabelGPTAFace;
extern lv_obj_t *ui_TextAreaAnswer;
void ui_event_SwitchSpeak( lv_event_t * e);
extern lv_obj_t *ui_SwitchSpeak;
extern lv_obj_t *ui_LabelGPTSwitch;
extern lv_obj_t *ui_LabelNoWiFi;
// SCREEN: ui_Game
void ui_Game_screen_init(void);
extern lv_obj_t *ui_Game;
void ui_event_GameBackToMain( lv_event_t * e);
extern lv_obj_t *ui_GameBackToMain;
// SCREEN: ui_Cal
void ui_Cal_screen_init(void);
extern lv_obj_t *ui_Cal;
void ui_event_CalBackToMain( lv_event_t * e);
extern lv_obj_t *ui_CalBackToMain;
extern lv_obj_t *ui_Calendar;
// SCREEN: ui_About
void ui_About_screen_init(void);
extern lv_obj_t *ui_About;
void ui_event_AboutBackToMain( lv_event_t * e);
extern lv_obj_t *ui_AboutBackToMain;
extern lv_obj_t *ui_Image2;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui_LabelAbout;
extern lv_obj_t *ui_LabelAbout1;
extern lv_obj_t *ui_LabelAbout2;
extern lv_obj_t *ui_LabelAbout3;
extern lv_obj_t *ui_Image3;
extern lv_obj_t *ui_Image5;
extern lv_obj_t *ui_Image6;
extern lv_obj_t *ui_LabelAbout4;
extern lv_obj_t *ui_LabelAbout5;
extern lv_obj_t *ui_Panel3;
extern lv_obj_t *ui_Image7;
extern lv_obj_t *ui_Image8;
extern lv_obj_t *ui_Image9;
extern lv_obj_t *ui_Label9;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_wifi2_png);   // assets\wifi2.png
LV_IMG_DECLARE( ui_img_wifi1_png);   // assets\wifi1.png
LV_IMG_DECLARE( ui_img_1760486568);   // assets\设置 (3).png
LV_IMG_DECLARE( ui_img_1841556803);   // assets\设置 (2).png
LV_IMG_DECLARE( ui_img_1974495044);   // assets\串口窗口 (2).png
LV_IMG_DECLARE( ui_img_1893424809);   // assets\串口窗口 (3).png
LV_IMG_DECLARE( ui_img_1248718756);   // assets\天气 (2).png
LV_IMG_DECLARE( ui_img_1329788991);   // assets\天气 (3).png
LV_IMG_DECLARE( ui_img_838277726);   // assets\网易云音乐.png
LV_IMG_DECLARE( ui_img_1587118764);   // assets\网易云音乐 (1).png
LV_IMG_DECLARE( ui_img_chatgpt_24_png);   // assets\ChatGPT_24.png
LV_IMG_DECLARE( ui_img_820875016);   // assets\ChatGPT_24 (1).png
LV_IMG_DECLARE( ui_img_1836259489);   // assets\游戏.png
LV_IMG_DECLARE( ui_img_1802314637);   // assets\游戏 (1).png
LV_IMG_DECLARE( ui_img_1146259266);   // assets\日历 (2).png
LV_IMG_DECLARE( ui_img_904179437);   // assets\日历 (1).png
LV_IMG_DECLARE( ui_img_2143026604);   // assets\关于我们.png
LV_IMG_DECLARE( ui_img_2034888330);   // assets\关于我们 (1).png
LV_IMG_DECLARE( ui_img_123003138);   // assets\back (2).png
LV_IMG_DECLARE( ui_img_684857571);   // assets\back (3).png
LV_IMG_DECLARE( ui_img_1744207828);   // assets\信息.png
LV_IMG_DECLARE( ui_img_1653814786);   // assets\发送.png
LV_IMG_DECLARE( ui_img_946281160);   // assets\发送 (1).png
LV_IMG_DECLARE( ui_img_538929268);   // assets\删除.png
LV_IMG_DECLARE( ui_img_1714323774);   // assets\删除 (1).png
LV_IMG_DECLARE( ui_img_1164226509);   // assets\对勾.png
LV_IMG_DECLARE( ui_img_1065442945);   // assets\对勾 (1).png
LV_IMG_DECLARE( ui_img_757343298);   // assets\叉叉 (3).png
LV_IMG_DECLARE( ui_img_1565204007);   // assets\叉叉 (2).png
LV_IMG_DECLARE( ui_img_886925217);   // assets\地点.png
LV_IMG_DECLARE( ui_img_1653150344);   // assets\温湿度.png
LV_IMG_DECLARE( ui_img_1416457588);   // assets\刷新-更新 (3).png
LV_IMG_DECLARE( ui_img_1416456565);   // assets\刷新-更新 (2).png
LV_IMG_DECLARE( ui_img_367312200);   // assets\播放 三角形.png
LV_IMG_DECLARE( ui_img_264944503);   // assets\播放.png
LV_IMG_DECLARE( ui_img_649016707);   // assets\play-上下切歌.png
LV_IMG_DECLARE( ui_img_113203703);   // assets\play-上下切歌 (1).png
LV_IMG_DECLARE( ui_img_123_png);   // assets\123.png
LV_IMG_DECLARE( ui_img_platformio_png);   // assets\platformio.png
LV_IMG_DECLARE( ui_img_959610608);   // assets\vscode (1).png
LV_IMG_DECLARE( ui_img_arduino_png);   // assets\arduino.png
LV_IMG_DECLARE( ui_img_966728820);   // assets\赞.png
LV_IMG_DECLARE( ui_img_1219345095);   // assets\投币激活@2x.png
LV_IMG_DECLARE( ui_img_1965006549);   // assets\收藏.png

LV_FONT_DECLARE( ui_font_AlimamaFont32Bpp4);
LV_FONT_DECLARE( ui_font_AlimamaShuHeiFont16Bpp4);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif