// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"
#include "config.h"
#include "task.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Main
void ui_Main_screen_init(void);
lv_obj_t * ui_Main;
lv_obj_t * ui_TabViewApp;
lv_obj_t * ui_TabPageApp;
lv_obj_t * ui_PanelSet;
void ui_event_ToSet(lv_event_t * e);
lv_obj_t * ui_ToSet;
lv_obj_t * ui_LabelSet;
lv_obj_t * ui_PanelSerial;
void ui_event_ToSerial(lv_event_t * e);
lv_obj_t * ui_ToSerial;
lv_obj_t * ui_LabelSerial;
lv_obj_t * ui_PanelWeather;
void ui_event_ToWeather(lv_event_t * e);
lv_obj_t * ui_ToWeather;
lv_obj_t * ui_LabelWeather;
lv_obj_t * ui_PanelMusic;
void ui_event_ToMusic(lv_event_t * e);
lv_obj_t * ui_ToMusic;
lv_obj_t * ui_LabelMusic;
lv_obj_t * ui_PanelGPT;
void ui_event_ToGPT(lv_event_t * e);
lv_obj_t * ui_ToGPT;
lv_obj_t * ui_LabelGPT;
lv_obj_t * ui_PanelGame;
void ui_event_ToGame(lv_event_t * e);
lv_obj_t * ui_ToGame;
lv_obj_t * ui_LabelGame;
lv_obj_t * ui_PanelCal;
void ui_event_ToCal(lv_event_t * e);
lv_obj_t * ui_ToCal;
lv_obj_t * ui_LabelCal;
lv_obj_t * ui_PanelAbout;
void ui_event_ToAbout(lv_event_t * e);
lv_obj_t * ui_ToAbout;
lv_obj_t * ui_LabelAbout;
lv_obj_t * ui_PanelTime;
lv_obj_t * ui_LabelTime1;
lv_obj_t * ui_LabelTime2;
lv_obj_t * ui_PanelInit;
lv_obj_t * ui_LabelInit;
lv_obj_t * ui_SwitchWiFi;
// CUSTOM VARIABLES


// SCREEN: ui_Set
void ui_Set_screen_init(void);
lv_obj_t * ui_Set;
void ui_event_SetBackToMain(lv_event_t * e);
lv_obj_t * ui_SetBackToMain;
lv_obj_t * ui_PanelLight;
void ui_event_SliderLight(lv_event_t * e);
lv_obj_t * ui_SliderLight;
lv_obj_t * ui_LabelLightValue;
lv_obj_t * ui_LabelLight;
lv_obj_t * ui_PanelWiFi;
void ui_event_RollerWiFi(lv_event_t * e);
lv_obj_t * ui_RollerWiFi;
lv_obj_t * ui_LabelWiFi;
void ui_event_OnOffWiFi(lv_event_t * e);
lv_obj_t * ui_OnOffWiFi;
void ui_event_EnterPass(lv_event_t * e);
lv_obj_t * ui_EnterPass;
lv_obj_t * ui_LabelPass;
lv_obj_t * ui_LabelWiFiState;
lv_obj_t * ui_PanelPass;
void ui_event_KeyboardPass(lv_event_t * e);
lv_obj_t * ui_KeyboardPass;
lv_obj_t * ui_PanelWiFiPass;
lv_obj_t * ui_TextAreaWiFiPass;
lv_obj_t * ui_LabelWiFiName;
void ui_event_CancelEnterPass(lv_event_t * e);
lv_obj_t * ui_CancelEnterPass;
lv_obj_t * ui_LabelCancel;
lv_obj_t * ui_SpinnerWiFi;
// CUSTOM VARIABLES


// SCREEN: ui_Serial
void ui_Serial_screen_init(void);
lv_obj_t * ui_Serial;
void ui_event_SerialBackToMain(lv_event_t * e);
lv_obj_t * ui_SerialBackToMain;
void ui_event_TextAreaTX(lv_event_t * e);
lv_obj_t * ui_TextAreaTX;
lv_obj_t * ui_TextAreaRX;
void ui_event_SerialTX(lv_event_t * e);
lv_obj_t * ui_SerialTX;
void ui_event_SerialDelete(lv_event_t * e);
lv_obj_t * ui_SerialDelete;
lv_obj_t * ui_KeyboardSerial;
// CUSTOM VARIABLES


// SCREEN: ui_Weather
void ui_Weather_screen_init(void);
lv_obj_t * ui_Weather;
lv_obj_t * ui_TabViewWeather;
lv_obj_t * ui_TabToday;
lv_obj_t * ui_ImageCode;
lv_obj_t * ui_ImageTemp;
lv_obj_t * ui_ImageLocation;
lv_obj_t * ui_LabelCode;
lv_obj_t * ui_LabelTemp;
lv_obj_t * ui_LabelLocation;
lv_obj_t * ui_LabelUpdateTime;
lv_obj_t * ui_TabFuture;
lv_obj_t * ui_RollerFuture;
lv_obj_t * ui_LabelTomorrowCode;
void ui_event_WeatherBackToMain(lv_event_t * e);
lv_obj_t * ui_WeatherBackToMain;
void ui_event_WeatherUpdate(lv_event_t * e);
lv_obj_t * ui_WeatherUpdate;
// CUSTOM VARIABLES


// SCREEN: ui_Music
void ui_Music_screen_init(void);
lv_obj_t * ui_Music;
void ui_event_MusicBackToMain(lv_event_t * e);
lv_obj_t * ui_MusicBackToMain;
lv_obj_t * ui_RollerMusic;
lv_obj_t * ui_PanelMusicSet;
void ui_event_StartMusic(lv_event_t * e);
lv_obj_t * ui_StartMusic;
void ui_event_ChangeMusic(lv_event_t * e);
lv_obj_t * ui_ChangeMusic;
void ui_event_LastMusic(lv_event_t * e);
lv_obj_t * ui_LastMusic;
void ui_event_NextMusic(lv_event_t * e);
lv_obj_t * ui_NextMusic;
void ui_event_PlayMusicMode(lv_event_t * e);
lv_obj_t * ui_PlayMusicMode;
void ui_event_SliderVoice(lv_event_t * e);
lv_obj_t * ui_SliderVoice;
lv_obj_t * ui_LabelVoice;
lv_obj_t * ui_LabelMusicName;
// CUSTOM VARIABLES


// SCREEN: ui_GPT
void ui_GPT_screen_init(void);
lv_obj_t * ui_GPT;
void ui_event_GPTBackToMain(lv_event_t * e);
lv_obj_t * ui_GPTBackToMain;
lv_obj_t * ui_TextAreaXiaozhiQuestion;
lv_obj_t * ui_ButtonXiaoZhiQuestion;
lv_obj_t * ui_LabelXiaoZhiQuestion;
lv_obj_t * ui_TextAreaXiaoZhiAnswer;
lv_obj_t * ui_ButtonXiaoZhiAnswer;
lv_obj_t * ui_LabelXiaoZhiAnswer;
void ui_event_SwitchXiaoZhiSpeak(lv_event_t * e);
lv_obj_t * ui_SwitchXiaoZhiSpeak;
lv_obj_t * ui_LabelXiaoZhiSpeak;
// CUSTOM VARIABLES


// SCREEN: ui_Game
void ui_Game_screen_init(void);
lv_obj_t * ui_Game;
void ui_event_GameBackToMain(lv_event_t * e);
lv_obj_t * ui_GameBackToMain;
void ui_event_ButtonGame2048(lv_event_t * e);
lv_obj_t * ui_ButtonGame2048;
lv_obj_t * ui_LabelGame2048;
void ui_event_ButtonGameYang(lv_event_t * e);
lv_obj_t * ui_ButtonGameYang;
lv_obj_t * ui_LabelGameYang;
void ui_event_ButtonGameXiao(lv_event_t * e);
lv_obj_t * ui_ButtonGameXiao;
lv_obj_t * ui_LabelGameXiao;
void ui_event_ButtonGamePvz(lv_event_t * e);
lv_obj_t * ui_ButtonGamePvz;
lv_obj_t * ui_LabelGamePvz;
// CUSTOM VARIABLES


// SCREEN: ui_Cal
void ui_Cal_screen_init(void);
lv_obj_t * ui_Cal;
void ui_event_CalBackToMain(lv_event_t * e);
lv_obj_t * ui_CalBackToMain;
lv_obj_t * ui_Calendar;
// CUSTOM VARIABLES


// SCREEN: ui_About
void ui_About_screen_init(void);
lv_obj_t * ui_About;
void ui_event_AboutBackToMain(lv_event_t * e);
lv_obj_t * ui_AboutBackToMain;
lv_obj_t * ui_ImageAboutMessage;
lv_obj_t * ui_LabelAboutMessage;
lv_obj_t * ui_ImageAbout1;
lv_obj_t * ui_ImageAbout2;
lv_obj_t * ui_ImageAbout3;
// CUSTOM VARIABLES


// SCREEN: ui_GameSon
void ui_GameSon_screen_init(void);
lv_obj_t * ui_GameSon;
void ui_event_GameSonBackToGame(lv_event_t * e);
lv_obj_t * ui_GameSonBackToGame;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_ToSet(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Set, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Set_screen_init);
        _ui_screen_delete(&ui_Main);

        // 创建WiFi任务
        WiFiTask_create();
    }
}

void ui_event_ToSerial(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Serial, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Serial_screen_init);
        _ui_screen_delete(&ui_Main);

        // 创建串口任务
        serialTask_create();
    }
}

void ui_event_ToWeather(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Weather, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Weather_screen_init);
        _ui_screen_delete(&ui_Main);
    }
}

void ui_event_ToMusic(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Music, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Music_screen_init);
        _ui_screen_delete(&ui_Main);
    }
}

void ui_event_ToGPT(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_GPT, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_GPT_screen_init);
        _ui_screen_delete(&ui_Main);
        
        // 创建小智任务
        xiaozhiTask_create();
    }
}

void ui_event_ToGame(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Game, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Game_screen_init);
        _ui_screen_delete(&ui_Main);
    }
}

void ui_event_ToCal(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Cal, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Cal_screen_init);
        _ui_screen_delete(&ui_Main);
    }
}

void ui_event_ToAbout(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_About, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_About_screen_init);
        _ui_screen_delete(&ui_Main);
    }
}

void ui_event_SetBackToMain(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Main, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Main_screen_init);
        _ui_screen_delete(&ui_Set);

        // 删除WiFi任务
        WiFiTask_delete();
    }
}

void ui_event_SliderLight(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_LabelLightValue, target, "", "%");
        Set.screen_light = lv_slider_get_value(target);
        if(Set.screen_light > 0)analogWrite(14, Set.screen_light*2.55);
    }
}

void ui_event_RollerWiFi(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        lv_roller_get_selected_str(ui_RollerWiFi, Set.WiFi_name, sizeof(Set.WiFi_name));
    }
}

void ui_event_OnOffWiFi(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_flag_modify(ui_RollerWiFi, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_EnterPass, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_LabelWiFiState, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        if(lv_obj_is_visible(ui_RollerWiFi))Set.WiFi_button_flag = 1;
        else 
        {
            WiFi.disconnect();
            Set.WiFi_connect_stauts = 0;
        }
    }
}

void ui_event_EnterPass(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_PanelPass, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        lv_label_set_text_fmt(ui_LabelWiFiName, "%s", Set.WiFi_name);
        lv_label_set_long_mode(ui_LabelWiFiName, LV_LABEL_LONG_SCROLL_CIRCULAR);
    }
}

void ui_event_KeyboardPass(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_READY) {
        _ui_flag_modify(ui_PanelPass, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_SpinnerWiFi, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        Set.WiFi_password = lv_textarea_get_text(ui_TextAreaWiFiPass);
        Set.WiFi_connect_flag = 1;
    }
}

void ui_event_CancelEnterPass(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_PanelPass, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_SerialBackToMain(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Main, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Main_screen_init);
        _ui_screen_delete(&ui_Serial);

        // 删除串口任务
        serialTask_delete();
    }
}

void ui_event_TextAreaTX(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_KeyboardSerial, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
    else if(event_code == LV_EVENT_VALUE_CHANGED) {
        Uart.tx_data = lv_textarea_get_text(target);
    }
}

void ui_event_SerialTX(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Serial.println(Uart.tx_data);
    }
}

void ui_event_SerialDelete(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        lv_textarea_set_text(ui_TextAreaRX, "");
    }
}

void ui_event_WeatherBackToMain(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Main, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Main_screen_init);
        _ui_screen_delete(&ui_Weather);
    }
}

void ui_event_WeatherUpdate(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Data.weather_flag = 1;
    }
}

void ui_event_MusicBackToMain(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Main, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Main_screen_init);
        _ui_screen_delete(&ui_Music);
    }
}

void ui_event_StartMusic(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_CLICKED) {
        if(lv_obj_has_state(target, LV_STATE_CHECKED))
        {
            Music.play_flag = 1;
            if(!Music.pause_flag)
                Music.start_flag = 1;
        }    
        else 
            Music.play_flag = 0;
    }
}

void ui_event_ChangeMusic(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Music.play_index = lv_roller_get_selected(ui_RollerMusic);
        lv_obj_add_state(ui_StartMusic, LV_STATE_CHECKED);
        lv_roller_set_selected(ui_RollerMusic, Music.play_index, LV_ANIM_OFF);
        lv_roller_get_selected_str(ui_RollerMusic, Music.song_name, sizeof(Music.song_name));
        lv_label_set_text_fmt(ui_LabelMusicName, "正在播放: %s", Music.song_name);
        Music.play_flag = 1;
        Music.start_flag = 1;
    }
}

void ui_event_LastMusic(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        if(Music.play_index == 0)
            Music.play_index = lv_roller_get_option_cnt(ui_RollerMusic) - 2;
        else 
            Music.play_index--;
        lv_obj_add_state(ui_StartMusic, LV_STATE_CHECKED);
        lv_roller_set_selected(ui_RollerMusic, Music.play_index, LV_ANIM_OFF);
        lv_roller_get_selected_str(ui_RollerMusic, Music.song_name, sizeof(Music.song_name));
        lv_label_set_text_fmt(ui_LabelMusicName, "正在播放: %s", Music.song_name);
        Music.play_flag = 1;
        Music.start_flag = 1;
    }
}

void ui_event_NextMusic(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        if(Music.play_index == lv_roller_get_option_cnt(ui_RollerMusic) - 2)
            Music.play_index = 0;
        else 
            Music.play_index++;
        lv_obj_add_state(ui_StartMusic, LV_STATE_CHECKED);
        lv_roller_set_selected(ui_RollerMusic, Music.play_index, LV_ANIM_OFF);
        lv_roller_get_selected_str(ui_RollerMusic, Music.song_name, sizeof(Music.song_name));
        lv_label_set_text_fmt(ui_LabelMusicName, "正在播放: %s", Music.song_name);
        Music.play_flag = 1;
        Music.start_flag = 1;
    }
}

void ui_event_PlayMusicMode(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        lv_obj_clear_state(ui_PlayMusicMode, LV_STATE_ANY);
        if(++Music.play_mode > 2)
            Music.play_mode = 0;
        // 单曲循环
        if(Music.play_mode == 0)
            lv_obj_add_state(ui_PlayMusicMode, LV_STATE_DEFAULT);
        // 顺序播放
        else if(Music.play_mode == 1)
            lv_obj_add_state(ui_PlayMusicMode, LV_STATE_USER_2);
        // 随机播放
        else if(Music.play_mode == 2)
            lv_obj_add_state(ui_PlayMusicMode, LV_STATE_USER_1);
    }
}

void ui_event_SliderVoice(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        Music.volume_value = lv_slider_get_value(ui_SliderVoice);
    }
}

void ui_event_GPTBackToMain(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Main, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Main_screen_init);
        _ui_screen_delete(&ui_GPT);

        // 删除小智任务
        xiaozhiTask_delete();
    }
}

void ui_event_SwitchXiaoZhiSpeak(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_checked_set_text_value(ui_LabelXiaoZhiSpeak, target, "ON", "OFF");
        if(lv_obj_has_state(target, LV_STATE_CHECKED))Xiaozhi.ask_flag = 1;
        else Xiaozhi.ask_flag = 0;
    }
}

void ui_event_GameBackToMain(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Main, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Main_screen_init);
        _ui_screen_delete(&ui_Game);
    }
}

void ui_event_ButtonGame2048(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_GameSon, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_GameSon_screen_init);
        _ui_screen_delete(&ui_Game);
        lv_obj_clean(ui_GameSon);
        game2048_update(ui_GameSon);

        ui_GameSonBackToGame = lv_imgbtn_create(ui_GameSon);
        lv_imgbtn_set_src(ui_GameSonBackToGame, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_back_released_png, NULL);
        lv_imgbtn_set_src(ui_GameSonBackToGame, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_back_pressed_png, NULL);
        lv_obj_set_width(ui_GameSonBackToGame, 32);
        lv_obj_set_height(ui_GameSonBackToGame, 32);
        lv_obj_set_x(ui_GameSonBackToGame, 2);
        lv_obj_set_y(ui_GameSonBackToGame, 8);
        lv_obj_add_event_cb(ui_GameSonBackToGame, ui_event_GameSonBackToGame, LV_EVENT_ALL, NULL);

        Music.play_flag = 1;
        Music.start_flag = 1;
        Game.game2048_flag = 1;

        if(lv_obj_has_state(ui_StartMusic, LV_STATE_CHECKED))
        {
            lv_obj_clear_state(ui_StartMusic, LV_STATE_CHECKED);
        }  
    }
}

void ui_event_ButtonGameYang(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_GameSon, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_GameSon_screen_init);
        _ui_screen_delete(&ui_Game);
        lv_obj_clean(ui_GameSon);
        yang_update(ui_GameSon);

        ui_GameSonBackToGame = lv_imgbtn_create(ui_GameSon);
        lv_imgbtn_set_src(ui_GameSonBackToGame, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_back_released_png, NULL);
        lv_imgbtn_set_src(ui_GameSonBackToGame, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_back_pressed_png, NULL);
        lv_obj_set_width(ui_GameSonBackToGame, 32);
        lv_obj_set_height(ui_GameSonBackToGame, 32);
        lv_obj_set_x(ui_GameSonBackToGame, 2);
        lv_obj_set_y(ui_GameSonBackToGame, 8);
        lv_obj_add_event_cb(ui_GameSonBackToGame, ui_event_GameSonBackToGame, LV_EVENT_ALL, NULL);

        Music.play_flag = 1;
        Music.start_flag = 1;
        Game.yang_flag = 1;

        if(lv_obj_has_state(ui_StartMusic, LV_STATE_CHECKED))
        {
            lv_obj_clear_state(ui_StartMusic, LV_STATE_CHECKED);
        }  
    }
}

void ui_event_ButtonGameXiao(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_GameSon, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_GameSon_screen_init);
        _ui_screen_delete(&ui_Game);
        lv_obj_clean(ui_GameSon);
        xiaoxiaole_update(ui_GameSon);

        ui_GameSonBackToGame = lv_imgbtn_create(ui_GameSon);
        lv_imgbtn_set_src(ui_GameSonBackToGame, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_back_released_png, NULL);
        lv_imgbtn_set_src(ui_GameSonBackToGame, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_back_pressed_png, NULL);
        lv_obj_set_width(ui_GameSonBackToGame, 32);
        lv_obj_set_height(ui_GameSonBackToGame, 32);
        lv_obj_set_x(ui_GameSonBackToGame, 2);
        lv_obj_set_y(ui_GameSonBackToGame, 8);
        lv_obj_add_event_cb(ui_GameSonBackToGame, ui_event_GameSonBackToGame, LV_EVENT_ALL, NULL);

        Music.play_flag = 1;
        Music.start_flag = 1;
        Game.xiaoxiaole_flag = 1;

        if(lv_obj_has_state(ui_StartMusic, LV_STATE_CHECKED))
        {
            lv_obj_clear_state(ui_StartMusic, LV_STATE_CHECKED);
        }  
    }
}

void ui_event_ButtonGamePvz(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_GameSon, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_GameSon_screen_init);
        _ui_screen_delete(&ui_Game);
        lv_obj_clean(ui_GameSon);
        pvz_update(ui_GameSon);

        ui_GameSonBackToGame = lv_imgbtn_create(ui_GameSon);
        lv_imgbtn_set_src(ui_GameSonBackToGame, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_back_released_png, NULL);
        lv_imgbtn_set_src(ui_GameSonBackToGame, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_back_pressed_png, NULL);
        lv_obj_set_width(ui_GameSonBackToGame, 32);
        lv_obj_set_height(ui_GameSonBackToGame, 32);
        lv_obj_set_x(ui_GameSonBackToGame, 2);
        lv_obj_set_y(ui_GameSonBackToGame, 8);
        lv_obj_add_event_cb(ui_GameSonBackToGame, ui_event_GameSonBackToGame, LV_EVENT_ALL, NULL);

        Music.play_flag = 1;
        Music.start_flag = 1;
        Game.pvz_flag = 1;
        if(lv_obj_has_state(ui_StartMusic, LV_STATE_CHECKED))
        {
            lv_obj_clear_state(ui_StartMusic, LV_STATE_CHECKED);
        }   
    }
}

void ui_event_CalBackToMain(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Main, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Main_screen_init);
        _ui_screen_delete(&ui_Cal);
    }
}

void ui_event_AboutBackToMain(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Main, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Main_screen_init);
        _ui_screen_delete(&ui_About);
    }
}

void ui_event_GameSonBackToGame(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Game, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Game_screen_init);
        _ui_screen_delete(&ui_GameSon);
        Music.play_flag = 0;
        Music.start_flag = 0;
        Game.game2048_flag = 0;
        Game.yang_flag = 0;
        Game.xiaoxiaole_flag = 0;
        Game.pvz_flag = 0;
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Main_screen_init();
    ui_Set_screen_init();
    ui_Serial_screen_init();
    ui_Weather_screen_init();
    ui_Music_screen_init();
    ui_GPT_screen_init();
    ui_Game_screen_init();
    ui_Cal_screen_init();
    ui_About_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Main);
}
