// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Main
void ui_Main_screen_init(void);
extern lv_obj_t * ui_Main;
extern lv_obj_t * ui_TabViewApp;
extern lv_obj_t * ui_TabPageApp;
extern lv_obj_t * ui_PanelSet;
void ui_event_ToSet(lv_event_t * e);
extern lv_obj_t * ui_ToSet;
extern lv_obj_t * ui_LabelSet;
extern lv_obj_t * ui_PanelSerial;
void ui_event_ToSerial(lv_event_t * e);
extern lv_obj_t * ui_ToSerial;
extern lv_obj_t * ui_LabelSerial;
extern lv_obj_t * ui_PanelWeather;
void ui_event_ToWeather(lv_event_t * e);
extern lv_obj_t * ui_ToWeather;
extern lv_obj_t * ui_LabelWeather;
extern lv_obj_t * ui_PanelMusic;
void ui_event_ToMusic(lv_event_t * e);
extern lv_obj_t * ui_ToMusic;
extern lv_obj_t * ui_LabelMusic;
extern lv_obj_t * ui_PanelGPT;
void ui_event_ToGPT(lv_event_t * e);
extern lv_obj_t * ui_ToGPT;
extern lv_obj_t * ui_LabelGPT;
extern lv_obj_t * ui_PanelGame;
void ui_event_ToGame(lv_event_t * e);
extern lv_obj_t * ui_ToGame;
extern lv_obj_t * ui_LabelGame;
extern lv_obj_t * ui_PanelCal;
void ui_event_ToCal(lv_event_t * e);
extern lv_obj_t * ui_ToCal;
extern lv_obj_t * ui_LabelCal;
extern lv_obj_t * ui_PanelAbout;
void ui_event_ToAbout(lv_event_t * e);
extern lv_obj_t * ui_ToAbout;
extern lv_obj_t * ui_LabelAbout;
extern lv_obj_t * ui_PanelTime;
extern lv_obj_t * ui_LabelTime1;
extern lv_obj_t * ui_LabelTime2;
extern lv_obj_t * ui_PanelInit;
extern lv_obj_t * ui_LabelInit;
extern lv_obj_t * ui_SwitchWiFi;
// CUSTOM VARIABLES

// SCREEN: ui_Set
void ui_Set_screen_init(void);
extern lv_obj_t * ui_Set;
void ui_event_SetBackToMain(lv_event_t * e);
extern lv_obj_t * ui_SetBackToMain;
extern lv_obj_t * ui_PanelLight;
void ui_event_SliderLight(lv_event_t * e);
extern lv_obj_t * ui_SliderLight;
extern lv_obj_t * ui_LabelLightValue;
extern lv_obj_t * ui_LabelLight;
extern lv_obj_t * ui_PanelWiFi;
void ui_event_RollerWiFi(lv_event_t * e);
extern lv_obj_t * ui_RollerWiFi;
extern lv_obj_t * ui_LabelWiFi;
void ui_event_OnOffWiFi(lv_event_t * e);
extern lv_obj_t * ui_OnOffWiFi;
void ui_event_EnterPass(lv_event_t * e);
extern lv_obj_t * ui_EnterPass;
extern lv_obj_t * ui_LabelPass;
extern lv_obj_t * ui_LabelWiFiState;
extern lv_obj_t * ui_PanelPass;
void ui_event_KeyboardPass(lv_event_t * e);
extern lv_obj_t * ui_KeyboardPass;
extern lv_obj_t * ui_PanelWiFiPass;
extern lv_obj_t * ui_TextAreaWiFiPass;
extern lv_obj_t * ui_LabelWiFiName;
void ui_event_CancelEnterPass(lv_event_t * e);
extern lv_obj_t * ui_CancelEnterPass;
extern lv_obj_t * ui_LabelCancel;
extern lv_obj_t * ui_SpinnerWiFi;
// CUSTOM VARIABLES

// SCREEN: ui_Serial
void ui_Serial_screen_init(void);
extern lv_obj_t * ui_Serial;
void ui_event_SerialBackToMain(lv_event_t * e);
extern lv_obj_t * ui_SerialBackToMain;
void ui_event_TextAreaTX(lv_event_t * e);
extern lv_obj_t * ui_TextAreaTX;
extern lv_obj_t * ui_TextAreaRX;
void ui_event_SerialTX(lv_event_t * e);
extern lv_obj_t * ui_SerialTX;
void ui_event_SerialDelete(lv_event_t * e);
extern lv_obj_t * ui_SerialDelete;
extern lv_obj_t * ui_KeyboardSerial;
// CUSTOM VARIABLES

// SCREEN: ui_Weather
void ui_Weather_screen_init(void);
extern lv_obj_t * ui_Weather;
extern lv_obj_t * ui_TabViewWeather;
extern lv_obj_t * ui_TabToday;
extern lv_obj_t * ui_ImageCode;
extern lv_obj_t * ui_ImageTemp;
extern lv_obj_t * ui_ImageLocation;
extern lv_obj_t * ui_LabelCode;
extern lv_obj_t * ui_LabelTemp;
extern lv_obj_t * ui_LabelLocation;
extern lv_obj_t * ui_LabelUpdateTime;
extern lv_obj_t * ui_TabFuture;
extern lv_obj_t * ui_RollerFuture;
extern lv_obj_t * ui_LabelTomorrowCode;
void ui_event_WeatherBackToMain(lv_event_t * e);
extern lv_obj_t * ui_WeatherBackToMain;
void ui_event_WeatherUpdate(lv_event_t * e);
extern lv_obj_t * ui_WeatherUpdate;
// CUSTOM VARIABLES

// SCREEN: ui_Music
void ui_Music_screen_init(void);
extern lv_obj_t * ui_Music;
void ui_event_MusicBackToMain(lv_event_t * e);
extern lv_obj_t * ui_MusicBackToMain;
extern lv_obj_t * ui_RollerMusic;
extern lv_obj_t * ui_PanelMusicSet;
void ui_event_StartMusic(lv_event_t * e);
extern lv_obj_t * ui_StartMusic;
void ui_event_ChangeMusic(lv_event_t * e);
extern lv_obj_t * ui_ChangeMusic;
void ui_event_LastMusic(lv_event_t * e);
extern lv_obj_t * ui_LastMusic;
void ui_event_NextMusic(lv_event_t * e);
extern lv_obj_t * ui_NextMusic;
void ui_event_PlayMusicMode(lv_event_t * e);
extern lv_obj_t * ui_PlayMusicMode;
void ui_event_SliderVoice(lv_event_t * e);
extern lv_obj_t * ui_SliderVoice;
extern lv_obj_t * ui_LabelVoice;
extern lv_obj_t * ui_LabelMusicName;
// CUSTOM VARIABLES

// SCREEN: ui_GPT
void ui_GPT_screen_init(void);
extern lv_obj_t * ui_GPT;
void ui_event_GPTBackToMain(lv_event_t * e);
extern lv_obj_t * ui_GPTBackToMain;
extern lv_obj_t * ui_TextAreaXiaozhiQuestion;
extern lv_obj_t * ui_ButtonXiaoZhiQuestion;
extern lv_obj_t * ui_LabelXiaoZhiQuestion;
extern lv_obj_t * ui_TextAreaXiaoZhiAnswer;
extern lv_obj_t * ui_ButtonXiaoZhiAnswer;
extern lv_obj_t * ui_LabelXiaoZhiAnswer;
void ui_event_SwitchXiaoZhiSpeak(lv_event_t * e);
extern lv_obj_t * ui_SwitchXiaoZhiSpeak;
extern lv_obj_t * ui_LabelXiaoZhiSpeak;
// CUSTOM VARIABLES

// SCREEN: ui_Game
void ui_Game_screen_init(void);
extern lv_obj_t * ui_Game;
void ui_event_GameBackToMain(lv_event_t * e);
extern lv_obj_t * ui_GameBackToMain;
void ui_event_ButtonGame2048(lv_event_t * e);
extern lv_obj_t * ui_ButtonGame2048;
extern lv_obj_t * ui_LabelGame2048;
void ui_event_ButtonGameYang(lv_event_t * e);
extern lv_obj_t * ui_ButtonGameYang;
extern lv_obj_t * ui_LabelGameYang;
void ui_event_ButtonGameXiao(lv_event_t * e);
extern lv_obj_t * ui_ButtonGameXiao;
extern lv_obj_t * ui_LabelGameXiao;
void ui_event_ButtonGamePvz(lv_event_t * e);
extern lv_obj_t * ui_ButtonGamePvz;
extern lv_obj_t * ui_LabelGamePvz;
// CUSTOM VARIABLES

// SCREEN: ui_Cal
void ui_Cal_screen_init(void);
extern lv_obj_t * ui_Cal;
void ui_event_CalBackToMain(lv_event_t * e);
extern lv_obj_t * ui_CalBackToMain;
extern lv_obj_t * ui_Calendar;
// CUSTOM VARIABLES

// SCREEN: ui_About
void ui_About_screen_init(void);
extern lv_obj_t * ui_About;
void ui_event_AboutBackToMain(lv_event_t * e);
extern lv_obj_t * ui_AboutBackToMain;
extern lv_obj_t * ui_ImageAboutMessage;
extern lv_obj_t * ui_LabelAboutMessage;
extern lv_obj_t * ui_ImageAbout1;
extern lv_obj_t * ui_ImageAbout2;
extern lv_obj_t * ui_ImageAbout3;
// CUSTOM VARIABLES

// SCREEN: ui_GameSon
void ui_GameSon_screen_init(void);
extern lv_obj_t * ui_GameSon;
void ui_event_GameSonBackToGame(lv_event_t * e);
extern lv_obj_t * ui_GameSonBackToGame;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_set_released_png);    // assets/Set_Released.png
LV_IMG_DECLARE(ui_img_set_pressed_png);    // assets/Set_Pressed.png
LV_IMG_DECLARE(ui_img_serial_released_png);    // assets/Serial_Released.png
LV_IMG_DECLARE(ui_img_serial_pressed_png);    // assets/Serial_Pressed.png
LV_IMG_DECLARE(ui_img_weather_released_png);    // assets/Weather_Released.png
LV_IMG_DECLARE(ui_img_weather_pressed_png);    // assets/Weather_Pressed.png
LV_IMG_DECLARE(ui_img_music_released_png);    // assets/Music_Released.png
LV_IMG_DECLARE(ui_img_music_pressed_png);    // assets/Music_Pressed.png
LV_IMG_DECLARE(ui_img_gpt_released_png);    // assets/GPT_Released.png
LV_IMG_DECLARE(ui_img_gpt_pressed_png);    // assets/GPT_Pressed.png
LV_IMG_DECLARE(ui_img_game_released_png);    // assets/Game_Released.png
LV_IMG_DECLARE(ui_img_game_pressed_png);    // assets/Game_Pressed.png
LV_IMG_DECLARE(ui_img_cal_released_png);    // assets/Cal_Released.png
LV_IMG_DECLARE(ui_img_about_released_png);    // assets/About_Released.png
LV_IMG_DECLARE(ui_img_wifi_pressed_png);    // assets/WiFi_Pressed.png
LV_IMG_DECLARE(ui_img_wifi_released_png);    // assets/WiFi_Released.png
LV_IMG_DECLARE(ui_img_back_released_png);    // assets/Back_Released.png
LV_IMG_DECLARE(ui_img_back_pressed_png);    // assets/Back_Pressed.png
LV_IMG_DECLARE(ui_img_serialsend_released_png);    // assets/SerialSend_Released.png
LV_IMG_DECLARE(ui_img_serialsend_pressed_png);    // assets/SerialSend_Pressed.png
LV_IMG_DECLARE(ui_img_serialdelete_released_png);    // assets/SerialDelete_Released.png
LV_IMG_DECLARE(ui_img_serialdelete_pressed_png);    // assets/SerialDelete_Pressed.png
LV_IMG_DECLARE(ui_img_weather_code_png);    // assets/Weather_Code.png
LV_IMG_DECLARE(ui_img_weather_temp_png);    // assets/Weather_Temp.png
LV_IMG_DECLARE(ui_img_weather_location_png);    // assets/Weather_Location.png
LV_IMG_DECLARE(ui_img_weatherupdate_released_png);    // assets/WeatherUpdate_Released.png
LV_IMG_DECLARE(ui_img_weatherupdate_pressed_png);    // assets/WeatherUpdate_Pressed.png
LV_IMG_DECLARE(ui_img_music_pause_png);    // assets/Music_Pause.png
LV_IMG_DECLARE(ui_img_music_play_png);    // assets/Music_Play.png
LV_IMG_DECLARE(ui_img_musicchange_released_png);    // assets/MusicChange_Released.png
LV_IMG_DECLARE(ui_img_musicchange_pressed_png);    // assets/MusicChange_Pressed.png
LV_IMG_DECLARE(ui_img_musiclast_released_png);    // assets/MusicLast_Released.png
LV_IMG_DECLARE(ui_img_musiclast_pressed_png);    // assets/MusicLast_Pressed.png
LV_IMG_DECLARE(ui_img_musicnext_released_png);    // assets/MusicNext_Released.png
LV_IMG_DECLARE(ui_img_musicnext_pressed_png);    // assets/MusicNext_Pressed.png
LV_IMG_DECLARE(ui_img_music_onceloop_png);    // assets/Music_OnceLoop.png
LV_IMG_DECLARE(ui_img_music_random_png);    // assets/Music_Random.png
LV_IMG_DECLARE(ui_img_music_orderloop_png);    // assets/Music_OrderLoop.png
LV_IMG_DECLARE(ui_img_about_message_png);    // assets/About_Message.png
LV_IMG_DECLARE(ui_img_about_luoxiaohei1_png);    // assets/About_LuoXiaoHei1.png
LV_IMG_DECLARE(ui_img_about_luoxiaohei3_png);    // assets/About_LuoXiaoHei3.png
LV_IMG_DECLARE(ui_img_about_luoxiaohei2_png);    // assets/About_LuoXiaoHei2.png

// FONTS
LV_FONT_DECLARE(ui_font_AlimamaShuHeiTiFont16Bpp4);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
