// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_About_screen_init(void)
{
ui_About = lv_obj_create(NULL);
lv_obj_clear_flag( ui_About, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_About, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_About, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AboutBackToMain = lv_imgbtn_create(ui_About);
lv_imgbtn_set_src(ui_AboutBackToMain, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_123003138, NULL);
lv_imgbtn_set_src(ui_AboutBackToMain, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_684857571, NULL);
lv_obj_set_height( ui_AboutBackToMain, 48);
lv_obj_set_width( ui_AboutBackToMain, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_AboutBackToMain, 2 );
lv_obj_set_y( ui_AboutBackToMain, 8 );

lv_color_t bg_color = lv_palette_lighten(LV_PALETTE_LIGHT_BLUE, 5);
lv_color_t fg_color = lv_palette_darken(LV_PALETTE_BLUE, 4);

const char* data = "https://space.bilibili.com/455474218";
lv_obj_t * qr = lv_qrcode_create(ui_About,58,fg_color, bg_color);
lv_qrcode_update(qr,data,strlen(data));
lv_obj_set_x( qr, -125 );
lv_obj_set_y( qr, 28 );
lv_obj_set_align( qr, LV_ALIGN_CENTER );

ui_Image2 = lv_img_create(ui_About);
lv_img_set_src(ui_Image2, &ui_img_123_png);
lv_obj_set_width( ui_Image2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Image2, -125 );
lv_obj_set_y( ui_Image2, -41 );
lv_obj_set_align( ui_Image2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label3 = lv_label_create(ui_About);
lv_obj_set_width( ui_Label3, 236);
lv_obj_set_height( ui_Label3, 20);
lv_obj_set_x( ui_Label3, 69 );
lv_obj_set_y( ui_Label3, -59 );
lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_Label3,LV_LABEL_LONG_SCROLL_CIRCULAR);
lv_label_set_text(ui_Label3,"ESP32S3-WROOM-1-N16R8");
lv_obj_set_style_text_font(ui_Label3, &ui_font_AlimamaShuHeiFont16Bpp4, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelAbout = ui_LabelAbout_create(ui_About);
lv_obj_set_x( ui_LabelAbout, -62 );
lv_obj_set_y( ui_LabelAbout, -60 );

ui_LabelAbout1 = ui_LabelAbout_create(ui_About);
lv_obj_set_width( ui_LabelAbout1, 70);
lv_obj_set_height( ui_LabelAbout1, 20);
lv_obj_set_x( ui_LabelAbout1, -52 );
lv_obj_set_y( ui_LabelAbout1, -37 );
lv_label_set_text(ui_LabelAbout1,"开发平台:");
lv_obj_set_style_text_color(ui_LabelAbout1, lv_color_hex(0xD76E31), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelAbout1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelAbout2 = ui_LabelAbout_create(ui_About);
lv_obj_set_width( ui_LabelAbout2, 59);
lv_obj_set_height( ui_LabelAbout2, 20);
lv_obj_set_x( ui_LabelAbout2, 53 );
lv_obj_set_y( ui_LabelAbout2, -35 );
lv_label_set_text(ui_LabelAbout2,"+        +");

ui_LabelAbout3 = ui_LabelAbout_create(ui_About);
lv_obj_set_width( ui_LabelAbout3, 297);
lv_obj_set_height( ui_LabelAbout3, 20);
lv_obj_set_x( ui_LabelAbout3, 61 );
lv_obj_set_y( ui_LabelAbout3, -13 );
lv_label_set_text(ui_LabelAbout3,"开发库:FreeRtos,LVGL,Audio");
lv_obj_set_style_text_color(ui_LabelAbout3, lv_color_hex(0x549EEF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelAbout3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image3 = lv_img_create(ui_About);
lv_img_set_src(ui_Image3, &ui_img_platformio_png);
lv_obj_set_width( ui_Image3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Image3, 62 );
lv_obj_set_y( ui_Image3, -32 );
lv_obj_set_align( ui_Image3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image3, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image5 = lv_img_create(ui_About);
lv_img_set_src(ui_Image5, &ui_img_959610608);
lv_obj_set_width( ui_Image5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Image5, 3 );
lv_obj_set_y( ui_Image5, -36 );
lv_obj_set_align( ui_Image5, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image5, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image6 = lv_img_create(ui_About);
lv_img_set_src(ui_Image6, &ui_img_arduino_png);
lv_obj_set_width( ui_Image6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Image6, 96 );
lv_obj_set_y( ui_Image6, -36 );
lv_obj_set_align( ui_Image6, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image6, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LabelAbout4 = ui_LabelAbout_create(ui_About);
lv_obj_set_width( ui_LabelAbout4, 244);
lv_obj_set_height( ui_LabelAbout4, 44);
lv_obj_set_x( ui_LabelAbout4, 37 );
lv_obj_set_y( ui_LabelAbout4, 62 );
lv_obj_set_align( ui_LabelAbout4, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelAbout4,"IC:MAX98357,MAX9814,ILI9341,     CST816S");
lv_obj_set_style_text_color(ui_LabelAbout4, lv_color_hex(0x6EC4C6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelAbout4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelAbout5 = ui_LabelAbout_create(ui_About);
lv_obj_set_width( ui_LabelAbout5, 226);
lv_obj_set_height( ui_LabelAbout5, 32);
lv_obj_set_x( ui_LabelAbout5, 27 );
lv_obj_set_y( ui_LabelAbout5, 16 );
lv_label_set_text(ui_LabelAbout5,"API支持:心知天气,阿里云,百                     度,MiniMax");
lv_obj_set_style_text_color(ui_LabelAbout5, lv_color_hex(0x9D68C2), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelAbout5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel3 = lv_obj_create(ui_About);
lv_obj_set_width( ui_Panel3, 134);
lv_obj_set_height( ui_Panel3, 43);
lv_obj_set_x( ui_Panel3, 0 );
lv_obj_set_y( ui_Panel3, 99 );
lv_obj_set_align( ui_Panel3, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_Panel3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image7 = lv_img_create(ui_Panel3);
lv_img_set_src(ui_Image7, &ui_img_966728820);
lv_obj_set_width( ui_Image7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Image7, -42 );
lv_obj_set_y( ui_Image7, 0 );
lv_obj_set_align( ui_Image7, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image7, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image8 = lv_img_create(ui_Panel3);
lv_img_set_src(ui_Image8, &ui_img_1219345095);
lv_obj_set_width( ui_Image8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Image8, 3 );
lv_obj_set_y( ui_Image8, 0 );
lv_obj_set_align( ui_Image8, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image8, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image8, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image9 = lv_img_create(ui_Panel3);
lv_img_set_src(ui_Image9, &ui_img_1965006549);
lv_obj_set_width( ui_Image9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Image9, 48 );
lv_obj_set_y( ui_Image9, 0 );
lv_obj_set_align( ui_Image9, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image9, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image9, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label9 = lv_label_create(ui_About);
lv_obj_set_width( ui_Label9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label9, 27 );
lv_obj_set_y( ui_Label9, -93 );
lv_obj_set_align( ui_Label9, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label9,"https://space.bilibili.com/455474218");
lv_obj_set_style_text_color(ui_Label9, lv_color_hex(0xFF719C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label9, 255, LV_PART_MAIN| LV_STATE_DEFAULT);


lv_obj_add_event_cb(ui_AboutBackToMain, ui_event_AboutBackToMain, LV_EVENT_ALL, NULL);

}
