// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"
#include "all_extern.h"

void ui_Music_screen_init(void)
{
ui_Music = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Music, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Music, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Music, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MusicBackToMain = lv_imgbtn_create(ui_Music);
lv_imgbtn_set_src(ui_MusicBackToMain, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_123003138, NULL);
lv_imgbtn_set_src(ui_MusicBackToMain, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_684857571, NULL);
lv_obj_set_height( ui_MusicBackToMain, 64);
lv_obj_set_width( ui_MusicBackToMain, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_MusicBackToMain, 2 );
lv_obj_set_y( ui_MusicBackToMain, 8 );

ui_RollerMusic = lv_roller_create(ui_Music);
lv_roller_set_options( ui_RollerMusic, songoptions, LV_ROLLER_MODE_NORMAL );
lv_obj_set_width( ui_RollerMusic, 270);
lv_obj_set_height( ui_RollerMusic, 166);
lv_obj_set_x( ui_RollerMusic, 15 );
lv_obj_set_y( ui_RollerMusic, -11 );
lv_obj_set_align( ui_RollerMusic, LV_ALIGN_CENTER );
lv_obj_set_style_text_font(ui_RollerMusic, &ui_font_AlimamaShuHeiFont16Bpp4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_RollerMusic, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_RollerMusic, lv_color_hex(0x90F7FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_RollerMusic, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_RollerMusic, 3, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_RollerMusic, lv_color_hex(0xD599FF), LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RollerMusic, 255, LV_PART_SELECTED| LV_STATE_DEFAULT);

ui_SliderVoice = lv_slider_create(ui_Music);
lv_slider_set_range(ui_SliderVoice, 0,21);
lv_slider_set_value( ui_SliderVoice, 10, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_SliderVoice)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_SliderVoice, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_SliderVoice, 17);
lv_obj_set_height( ui_SliderVoice, 114);
lv_obj_set_x( ui_SliderVoice, 13 );
lv_obj_set_y( ui_SliderVoice, -16 );
lv_obj_set_align( ui_SliderVoice, LV_ALIGN_LEFT_MID );

lv_obj_set_style_bg_color(ui_SliderVoice, lv_color_hex(0x8BF6FF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SliderVoice, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_SliderVoice, lv_color_hex(0xD098FF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SliderVoice, 255, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_PanelMusicSet = lv_obj_create(ui_Music);
lv_obj_set_width( ui_PanelMusicSet, 270);
lv_obj_set_height( ui_PanelMusicSet, 45);
lv_obj_set_x( ui_PanelMusicSet, 15 );
lv_obj_set_y( ui_PanelMusicSet, -6 );
lv_obj_set_align( ui_PanelMusicSet, LV_ALIGN_BOTTOM_MID );
lv_obj_clear_flag( ui_PanelMusicSet, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_PanelMusicSet, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PanelMusicSet, lv_color_hex(0xDCAAFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PanelMusicSet, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_PanelMusicSet, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_PanelMusicSet, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_StartMusic = lv_switch_create(ui_PanelMusicSet);
lv_obj_set_width( ui_StartMusic, 50);
lv_obj_set_height( ui_StartMusic, 40);
lv_obj_set_x( ui_StartMusic, -75 );
lv_obj_set_y( ui_StartMusic, 0 );
lv_obj_set_align( ui_StartMusic, LV_ALIGN_RIGHT_MID );
lv_obj_set_style_bg_color(ui_StartMusic, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_StartMusic, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_StartMusic, &ui_img_367312200, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_color(ui_StartMusic, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_StartMusic, 0, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_bg_img_src( ui_StartMusic, &ui_img_264944503, LV_PART_MAIN | LV_STATE_CHECKED );

lv_obj_set_style_bg_color(ui_StartMusic, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_StartMusic, 0, LV_PART_INDICATOR| LV_STATE_CHECKED);

lv_obj_set_style_bg_color(ui_StartMusic, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_StartMusic, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_StartMusic, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_StartMusic, 0, LV_PART_KNOB| LV_STATE_CHECKED);

ui_ChangeMusic = lv_imgbtn_create(ui_PanelMusicSet);
lv_imgbtn_set_src(ui_ChangeMusic, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_649016707, NULL);
lv_imgbtn_set_src(ui_ChangeMusic, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_113203703, NULL);
lv_obj_set_height( ui_ChangeMusic, 32);
lv_obj_set_width( ui_ChangeMusic, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_ChangeMusic, 83 );
lv_obj_set_y( ui_ChangeMusic, 0 );
lv_obj_set_align( ui_ChangeMusic, LV_ALIGN_LEFT_MID );

ui_Label1 = lv_label_create(ui_Music);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label1, -139 );
lv_obj_set_y( ui_Label1, 67 );
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"声音");
lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0x1095DE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label1, &ui_font_AlimamaShuHeiFont16Bpp4, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_MusicBackToMain, ui_event_MusicBackToMain, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_RollerMusic, ui_event_RollerMusic, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_SliderVoice, ui_event_SliderVoice, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_StartMusic, ui_event_StartMusic, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ChangeMusic, ui_event_ChangeMusic, LV_EVENT_ALL, NULL);

}