// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"


// COMPONENT LabelAbout

lv_obj_t *ui_LabelAbout_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_LabelAbout;
cui_LabelAbout = lv_label_create(comp_parent);
lv_obj_set_width( cui_LabelAbout, 50);
lv_obj_set_height( cui_LabelAbout, 20);
lv_obj_set_x( cui_LabelAbout, -33 );
lv_obj_set_y( cui_LabelAbout, -60 );
lv_obj_set_align( cui_LabelAbout, LV_ALIGN_CENTER );
lv_label_set_text(cui_LabelAbout,"主控:");
lv_obj_set_style_text_font(cui_LabelAbout, &ui_font_AlimamaShuHeiFont16Bpp4, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_LABELABOUT_NUM);
children[UI_COMP_LABELABOUT_LABELABOUT] = cui_LabelAbout;
lv_obj_add_event_cb(cui_LabelAbout, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_LabelAbout, del_component_child_event_cb, LV_EVENT_DELETE, children);
ui_comp_LabelAbout_create_hook(cui_LabelAbout);
return cui_LabelAbout; 
}

