// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_COMP_LABELABOUT_H
#define _UI_COMP_LABELABOUT_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT LabelAbout
#define UI_COMP_LABELABOUT_LABELABOUT 0
#define _UI_COMP_LABELABOUT_NUM 1
lv_obj_t *ui_LabelAbout_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
