// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"


// COMPONENT ImageLab

lv_obj_t *ui_ImageLab_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_ImageLab;
cui_ImageLab = lv_img_create(comp_parent);
lv_obj_set_width( cui_ImageLab, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_ImageLab, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_ImageLab, 21 );
lv_obj_set_y( cui_ImageLab, 2 );
lv_obj_set_align( cui_ImageLab, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( cui_ImageLab, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( cui_ImageLab, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_IMAGELAB_NUM);
children[UI_COMP_IMAGELAB_IMAGELAB] = cui_ImageLab;
lv_obj_add_event_cb(cui_ImageLab, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_ImageLab, del_component_child_event_cb, LV_EVENT_DELETE, children);
ui_comp_ImageLab_create_hook(cui_ImageLab);
return cui_ImageLab; 
}

